### ISSUE TITLE
TypeScript: UserbackWidgetSettings interface shipped with npm module is wrong / malformed.

### ISSUE THREAD

**Issue by josheverett** [userback/widget-js#23]
Interface in source:

<img width="731" alt="image" src="https://user-images.githubusercontent.com/151150/187823601-67b05988-94f0-4748-af9a-dfc24e2a521f.png">

Interface in the npm module's `widget/dist/widget.d.ts` file:

<img width="589" alt="image" src="https://user-images.githubusercontent.com/151150/187823663-1aa9cf4b-f360-42d8-ae94-66aafc84bffc.png">

Notice the nested `widgetSettings` property.

As a result of this, the following makes TypeScript happy, but doesn't properly configure the widget:

```ts
<UserbackProvider
  token={TOKEN}
  widgetSettings={{ widgetSettings: { trigger_type: 'api' } }}
>
  ...
</UserbackProvider>
```

While TypeScript complains about this, but the widget is properly configured:

```ts
<UserbackProvider
  token={TOKEN}
  widgetSettings={{ trigger_type: 'api' }}
>
  ...
</UserbackProvider>
```

**Comment by Shard** [comment]
Hi @josheverett, Thank you for pointing out this issue to us! 

There was a unreleased fix to this that I had not got around to publishing so i have cut a new [v0.1.2](https://github.com/userback/widget-js/releases/tag/v0.1.2) release to resolve this.

Let us know if your still having an issue with the types and we can re-open this issue, otherwise feel free to report any other issues you might have!

Cheers
